language: node_js
node_js:
  - "0.10"
  - "0.12"
sudo: false
cache:
  directories:
    - node_modules
env:
before_install:
  - pwd
  - git clone https://github.com/timeoff-management/application.git ~/tom
  - cd ~/tom
before_script:
  - node bin/wwww > /dev/null &
